### ISSUE TITLE
Console error after Webpack uglify

### ISSUE THREAD

**Issue by MWDelaney** [electerious/basicScroll#13] opened 2018-03-07 15:24 UTC
Hi,
I'm trying to include basicScroll in a Roots/[Sage](https://github.com/roots/sage) project and I'm getting a console error after building my assets for production.

```
TypeError: l is not a function. (In 'l(t,c,f,h)', 'l' is 4)
```

I'm not the most webpack savvy user, so my troubleshooting is limited. The library works great when the assets aren't uglified, but throw the above error in the browser console when the webpack bundle is uglified.

I've tried separating basicScroll into its own separate script file (still uglified) with the same result. I've also tried a fresh copy of Sage with no other (non-default) dependencies, also with the same result.

I'm happy to try any more troubleshooting steps you can suggest. Thank you for your time and for this awesome library.

**Comment by vasilisakarelova** [comment] 2018-03-16 07:19
I had the exact same problem! The quick solution that i found so far, to make it at least work was (i have a React SPA) i added to my html file script with this code - _https://raw.githubusercontent.com/electerious/basicScroll/master/dist/basicScroll.min.js_ -  and in my components assigned a variable like `const basicScroll = window.basicScroll`. That worked for me. Try it yourself.

**Comment by electerious** [comment] 2018-04-19 11:45
Are you using uglify or uglify-es? It might be a bug with the newest version (uglify-es) as re-minifying works with fine for me with uglify.

It would be great if someone could open an issue on the tool causing the issues.

**Comment by electerious** [comment] 2018-04-30 15:21
I've opened an issue in the `uglify-es` repository as `uglifyjs-webpack-plugin` relies on `uglify-es`: https://github.com/mishoo/UglifyJS2/issues/3109

@MWDelaney @aaronwaldon Recompressing basicScroll.min.js with `uglify-es` works fine, too. Can you please show us how you're using and importing basicScroll?

**Comment by aaronwaldon** [comment] 2018-08-10 17:26
I believe the issue was caused by using the webpack.optimize.UglifyJsPlugin in Webpack 3. I have since migrated to Webpack 4 and switched to the TerserPlugin, and everything seems to be working as expected. Thank you for the help and guidance!

**Comment by electerious** [comment] 2018-08-11 13:54
Good to hear :) I will close the issue as I have no clue what's causing it. Will reopen when necessary.

**Closed as completed by electerious** 2018-08-11 13:54 UTC
